# Generated by Django 4.1.3 on 2022-12-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsstory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={},
        ),
    ]
