# Generated by Django 4.1.3 on 2022-12-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_field',
            field=models.URLField(default='\\images\\ollie.jpg'),
        ),
    ]
