# Generated by Django 4.1.3 on 2022-12-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsstory_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_field',
            field=models.URLField(blank=True),
        ),
    ]
