# Generated by Django 4.1.3 on 2022-12-12 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0008_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='story',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
